CREATE TABLE IF NOT EXISTS usuario (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS sessao (
    id SERIAL PRIMARY KEY,
    usuario_id INTEGER REFERENCES usuario(id) ON DELETE CASCADE,
    session_id VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS plataforma (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS serie (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    temporadas INTEGER DEFAULT 1,
    id_plataforma INTEGER REFERENCES plataforma(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS episodio (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    numero INTEGER NOT NULL,
    id_serie INTEGER REFERENCES serie(id) ON DELETE SET NULL
);
